### ISSUE TITLE
Is there a way to log the passwords?

### ISSUE THREAD

**Issue by FuckTheFreeWorld** [SkrewEverything/Swift-Keylogger#10]
I have read the README.md about **EnableSecureEventInput**. But is there any way to log the passwords? I really need that. 

Please Help me🙏🏻

**Comment by SkrewEverything** [comment]
@FuckTheFreeWorld 

![22688825_158650658061161_835696587617695758_n](https://user-images.githubusercontent.com/15038803/32075487-96378c10-baba-11e7-8883-58641e9edf5a.jpg)

**Comment by FuckTheFreeWorld** [comment]
@SkrewEverything I'm gonna pay for it!

**Comment by SkrewEverything** [comment]
@FuckTheFreeWorld Ok. When the project becomes popular then I will update the repo with your request. 
I don't want Apple to fix it before anyone knows or utilizes it.

**Comment by moliata** [comment]
@SkrewEverything private message? 😊

**Comment by SkrewEverything** [comment]
@moliata What does "private message" mean?

**Comment by moliata** [comment]
![screen shot 2018-07-08 at 10 16 33](https://user-images.githubusercontent.com/7127204/42417646-08f29af6-8298-11e8-8c3b-2322c9c0beb6.png)

**Comment by SkrewEverything** [comment]
@moliata What do you want specifically? The email is for the people who want to contact me for work/questions/project related queries.

**Comment by moliata** [comment]
"There is a possibility. But should I reveal? NO!" quoting that.
