### ISSUE TITLE
Can't open HID!

### ISSUE THREAD

**Issue by nitin0451** [SkrewEverything/Swift-Keylogger#17]
Hi, 

First of all thanks for the code, you are helping a lot a developers here.
I am using macos Catalina (10.15.4) and i am facing an issue i.e "Can't open HID!". I am running it on my imac with keypad and trackpad.

Please help me to resolve this.
Thanks in Advance.

**Comment by SkrewEverything** [comment]
Hi @nitin0451 ,

This issue has been opened by many people before you and most of them deleted the issue.

Anyway, 
How are you running it? By downloading the source and running it? Or by downloading the binary from Releases tab? If it is from releases tab, try to download the project and run it from Xcode. macOS Catalina has introduced so many new security features and it might be causing issues for downloaded binary. So, try to download the source and open the Xcode project file in your Xcode and just run it. (No need of complex setup or setting up dependencies.)

I suggested this solution for others and they never updated me but they deleted the issue. So, I'm guessing it solved their issue.

Try it and update me.

**Comment by akashnimare** [comment]
@SkrewEverything all good on macOS Catalina 10.15.3, works like a charm. Here is what I did -
* Clone the repo locally
* Open the project in Xcode
* Run build
* Run the binary
* For the first time, it asks for the permission
* That's it

**Comment by phucnd0604** [comment]
i have the same issue when import the source code. My app need to modify some setting when log to file.
is there any setting to use source code files?
