### ISSUE TITLE
Key Repeats

### ISSUE THREAD

**Issue by achalagarwal** [SkrewEverything/Swift-Keylogger#18]
Long pressed keys get logged only once (even though they might be getting typed multiple times if `key repeat` is enabled).

Is it possible to get the exact count in the logs?

It might not be a big change because for special keys (shift, ctrl, option) I think we have something similar to the keyPress and keyRelease callbacks?

**Comment by SkrewEverything** [comment]
Hi @achalagarwal 

I have 2 reasons for not implementing this behaviour.
----

**Reason: 1**

I thought of doing it initially but after some googling, I realised it is based on OS behaviour. 

On low-level, the system only detects whether a key is pressed or released.

macOS decides what to do based on the settings in **Settings.app**
<img width="780" alt="Screenshot 2020-11-22 at 6 51 02 PM" src="https://user-images.githubusercontent.com/15038803/99904858-ae6d3600-2cf3-11eb-9edf-11cd9c0d2917.png">

This functionality can be done by getting settings data and using timers and if statements.

But, long-pressing a key displays a  popup to select accented characters like this:

![image](https://user-images.githubusercontent.com/15038803/99904986-0efc7300-2cf4-11eb-84ba-4d7c1f797f61.png)

The accented characters can either be selected by pressing the corresponding number or clicking on the character directly, which can't be detected accurately. 

Again, this behaviour can be disabled but only through the terminal like [this](https://apple.stackexchange.com/a/332770/194093). But some users prefer getting this popup.

    defaults write -g ApplePressAndHoldEnabled -bool false

Implementing all these(timers, preferences etc) would have become too complex for others to extend the functionality based on their needs and also, there is a lot of probability for false positives. So, I decided not to include the functionality.

---

**Reason 2:**

Another reason is, as far as I have seen, no one presses the key to type repeated characters, which are meaningful. We only long-press the key when we want to spam a certain character without a proper meaning or to move the cursor or modifier keys. None of them makes sense to log multiple times. 

So, making the keylogger's implementation complex just for a very small percentage of users(maybe you might have a proper use-case) seemed completely unnecessary for me.

**Comment by achalagarwal** [comment]
Thanks @SkrewEverything 

Your points are justified. I would like to modify your implementation to get the `key release` and `key pressed` signals. 

Do you have an entry function in mind, from where I could start tinkering/digging?

**Comment by SkrewEverything** [comment]
In [CallBackFunction.swift](https://github.com/SkrewEverything/Swift-Keylogger/blob/master/Keylogger/Keylogger/CallBackFunctions.swift) file:

 - From [Line 109](https://github.com/SkrewEverything/Swift-Keylogger/blob/master/Keylogger/Keylogger/CallBackFunctions.swift#L109) to [Line 132](https://github.com/SkrewEverything/Swift-Keylogger/blob/master/Keylogger/Keylogger/CallBackFunctions.swift#L132) deals with the fileName(current active/focused app) and writes the timestamp to that particular app named file

 - From [Line 133](https://github.com/SkrewEverything/Swift-Keylogger/blob/master/Keylogger/Keylogger/CallBackFunctions.swift#L133) to [Line 162](https://github.com/SkrewEverything/Swift-Keylogger/blob/master/Keylogger/Keylogger/CallBackFunctions.swift#L162) deals with which key has been pressed and writes that keypress to the file.

In [Keylogger.swift](https://github.com/SkrewEverything/Swift-Keylogger/blob/master/Keylogger/Keylogger/Keylogger.swift) file:

 - From [Line 145](https://github.com/SkrewEverything/Swift-Keylogger/blob/master/Keylogger/Keylogger/Keylogger.swift#L145) to [Line 256](https://github.com/SkrewEverything/Swift-Keylogger/blob/master/Keylogger/Keylogger/Keylogger.swift#L256) has the mappings of the keyboard keys(QWERTY) corresponding to the keycode(produced in [CallBackFunction.swift](https://github.com/SkrewEverything/Swift-Keylogger/blob/master/Keylogger/Keylogger/CallBackFunctions.swift) file From [Line 133](https://github.com/SkrewEverything/Swift-Keylogger/blob/master/Keylogger/Keylogger/CallBackFunctions.swift#L133) to [Line 162](https://github.com/SkrewEverything/Swift-Keylogger/blob/master/Keylogger/Keylogger/CallBackFunctions.swift#L162) ).
