### ISSUE TITLE
Key's not getting logged when using Karabiner on mac

### ISSUE THREAD

**Issue by yanshiyason** [SkrewEverything/Swift-Keylogger#3]
Hi, thank you so much for making this!
I learned a lot by going through your code!

I was able to get it to compile after upgrading to Swift 4 and Xcode 9.0 beta.

I use [Karabiner-Element](https://github.com/tekezo/Karabiner-Elements) to remap the keys on my keyboard.

When Karabiner is turned on, the Keylogger is writing logs to `Data/Apps` and `Data/Devices` but nothing in `Data/Keys`.

Here is the the output of `Data/Devices`

```
cat Data/Devices/19-8-2017/Time\ Stamps
Connected - Saturday, August 19, 2017 at 7:46:18 PM Japan Standard Time	<IOHIDDevice 0x7ff675601220 [0x7fffe4f0bda0] 'ClassName=AppleHSSPIHIDDriver'  Transport=SPI VendorID=1452 ProductID=627 Product=Apple Internal Keyboard / Trackpad PrimaryUsagePage=1 PrimaryUsage=6 ReportInterval=8000>
Connected - Saturday, August 19, 2017 at 7:46:18 PM Japan Standard Time	<IOHIDDevice 0x7ff6756009d0 [0x7fffe4f0bda0] 'ClassName=org_pqrs_driver_Karabiner_VirtualHIDDevice_VirtualHIDKeyboard_v040600'  VendorID=0 ProductID=0 Manufacturer=pqrs.org Product=Karabiner VirtualHIDKeyboard PrimaryUsagePage=1 PrimaryUsage=6 ReportInterval=8000>
```

I will try to debug this on my own time as soon as possible. If you have any idea on top of your head about where the problem may lie, any advice would be greatly appreciated!

Thanks again for this amazing program!

**Comment by SkrewEverything** [comment]
@yanshiyason I just tried and I noticed that Keylogger is not logging keys when Karabiner is running. When the Karabiner is closed, the keylogger is working fine. 

I will try to patch the bug but currently I'm too busy to work on this. If you find a fix, please submit a pull request or solution. Your help will be greatly appreciated.

**Comment by yanshiyason** [comment]
Ok, so I did a little bit of research.

The screenshots bellow shows 2 terminals side by side.
I start the Keylogger with the `nohup ./Keylogger &` command on the left, and I display logs on the right.

Here are the logs without karabiner.:
![image](https://user-images.githubusercontent.com/11358371/29488233-b9933c94-8541-11e7-90c5-585e36867386.png)
The `observer` is receiving the `InputValueCallback`s no problem. If I switch karabiner on, it stops working and starts working again when I turn karabiner off.

Here are the logs when I start the Keylogger with Karabiner turned on:
![image](https://user-images.githubusercontent.com/11358371/29488238-c44a410a-8541-11e7-825c-e7e0da2c6899.png)

The `observer` doesn't receive any events, even if I turn karabiner off.

The karabiner preferences panel has a `Log` section, whre I think I found the problem:
![image](https://user-images.githubusercontent.com/11358371/29488314-14f449c4-8543-11e7-96a0-49870220c5cd.png)
As you can see, it says
```
1) Karabiner VirtualHIDKeyboard (device_id:3) is detected.
2) Apple Internal Keyboard / Trackpad (device_id:2) is ignored.
3) Apple Internal Keyboard / Trackpad (device_id:1) is grabbed
```
and in the `virtual keyboard` pane,  it says all events are redirected to the `Karabiner VirtualHIDKeyboard`:

![image](https://user-images.githubusercontent.com/11358371/29488324-590aed20-8543-11e7-8a8e-2566adcccf73.png)

So I think that in order to support Karabiner, we would actually need to add here:

![image](https://user-images.githubusercontent.com/11358371/29488350-cfbfef2e-8543-11e7-944c-677c8174fca2.png)

Instead of the `Generic Desktop Keyboard`, we would need to somehow add [Karabiner's VirtualHIDKeyboard](https://github.com/tekezo/Karabiner-Elements/tree/master/src/vendor/Karabiner-VirtualHIDDevice), which I have no idea how to even start going about...

Any thoughts?

**Comment by SkrewEverything** [comment]
@yanshiyason I think I found the problem.

As I mentioned in the Readme.md, it doesn't capture [EnableSecureEventInput](https://developer.apple.com/library/content/technotes/tn2150/_index.html) and Karabiner uses EnableSecureEventInput in its code.

![image](https://user-images.githubusercontent.com/15038803/29488995-bb1012d0-8533-11e7-9f80-67ff96c99a85.png)

You can find the value `kIOHIDOptionsTypeSeizeDevice` in [Karabiner-Elements/src/share/human_interface_device.hpp](https://github.com/tekezo/Karabiner-Elements/blob/master/src/share/human_interface_device.hpp#L389).

So that is the reason the keylogger can't log the key strokes.
