### ISSUE TITLE
Keyboard events are going to have cut off after several hours.

### ISSUE THREAD

**Issue by genki** [SkrewEverything/Swift-Keylogger#4]
I have tested this program, it runs well as expected for a while.
But after several hours, suddenly events regarding keyboard had cut off.
Other events are still going well.

I am using macOS 10.12.6 on MacBook Pro (13-inch, Late 2016, Four Thunderbolt 3 Ports)

Does anyone haven't experienced similar issues?

**Comment by SkrewEverything** [comment]
@genki Can you tell me the exact start and end time of keystroke in logging file?

**Comment by unkownymouse** [comment]
@genki @SkrewEverything I'm running the keylogger continuously from 4 weeks and there is no problem. 

@genki I think some other program is enabling secure key event in your mac. Check the [issue#3](https://github.com/SkrewEverything/Swift-Keylogger/issues/3)

**Comment by SkrewEverything** [comment]
@genki I have tested it for almost 1 month continuously running and I don't see any problems. As @unkownymouse suggested, check out the issue#3. It might be the problem.
