### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by unkownymouse** [SkrewEverything/Swift-Keylogger#9]
I just want to say thank you for this great project which helped me a lot in my project. I submitted my project for a contest and I won the contest and got some money.

I just want to donate the money to you for creating such great project.

So, how can I donate to you?

**Comment by SkrewEverything** [comment]
@unkownymouse It's just a waste of time to set up an account. I don't think anyone other than you will be donating. So, if there are more people like you then I might think about it.

**Comment by FuckTheFreeWorld** [comment]
Count me in!
